/** Stable machine-readable pubkey protocol error codes. */
export const ERROR_CODES = Object.freeze({
	invalid_signature: "invalid_signature",
	unknown_principal: "unknown_principal",
	master_key_not_armed: "master_key_not_armed",
	master_key_replacement_requires_otp: "master_key_replacement_requires_otp",
	timestamp_out_of_window: "timestamp_out_of_window",
	nonce_replayed: "nonce_replayed",
	unsupported_protocol_version: "unsupported_protocol_version",
	unsupported_algorithm: "unsupported_algorithm",
	invalid_public_key: "invalid_public_key",
	invalid_proof_of_possession: "invalid_proof_of_possession",
	key_id_conflict: "key_id_conflict",
	capability_mismatch: "capability_mismatch",
	otp_invalid: "otp_invalid",
	otp_expired: "otp_expired",
	principal_mismatch: "principal_mismatch",
	email_not_canonical: "email_not_canonical",
	invalid_email: "invalid_email",
	vault_conflict: "vault_conflict",
	vault_integrity: "vault_integrity",
	provider_unavailable: "provider_unavailable",
	hardware_protection_unavailable: "hardware_protection_unavailable",
	key_not_found: "key_not_found",
	key_not_exportable: "key_not_exportable",
	key_import_failure: "key_import_failure",
	vault_locked: "vault_locked",
	vault_corrupt: "vault_corrupt",
	vault_authentication_failure: "vault_authentication_failure",
	vault_revision_conflict: "vault_revision_conflict",
	signature_failure: "signature_failure",
	server_signature_rejection: "server_signature_rejection",
	replay_rejection: "replay_rejection",
	clock_skew: "clock_skew",
	protocol_version_mismatch: "protocol_version_mismatch",
	device_not_authorized: "device_not_authorized",
	device_revoked: "device_revoked",
	enrollment_expired: "enrollment_expired",
	enrollment_replayed: "enrollment_replayed",
	enrollment_rejected: "enrollment_rejected",
	enrollment_commitment_mismatch: "enrollment_commitment_mismatch",
	otp_not_device_enrollment: "otp_not_device_enrollment",
	msk_envelope_missing: "msk_envelope_missing",
	unsupported_structure_version: "unsupported_structure_version",
});

export const ERROR_CODE_LIST = Object.freeze(Object.values(ERROR_CODES));
